/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_cognito_identity_pool_id": "eu-north-1:92e36810-2f1b-4866-be85-ff49d3991693",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_bKl8shmd3",
    "aws_user_pools_web_client_id": "7jpi11ra353h1nadammqhm2jtd",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_dynamodb_all_tables_region": "eu-north-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "usersTable-dev",
            "region": "eu-north-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "manageTasks",
            "endpoint": "https://n4tv7n6nt9.execute-api.eu-north-1.amazonaws.com/dev",
            "region": "eu-north-1"
        }
    ]
};


export default awsmobile;
